### PR TITLE
Fixed some of the errors and finalized

### LINKED ISSUE #36: STAGE 13 — Wiring It All Together: Program.Main()

### PR DESCRIPTION
**Pull request by Themba-CTU**
🚨 Omin ALERT 🚨  
This code was NOT written... it was COOKED 🍳🔥  

The guys were there too… doing their absolute best (minimum) as usual 🛋️😴  

And then... Victoria 👑✨  

Victoria didn’t just contribute — she **spearheaded the entire operation** like a noble, battle-hardened commander of clean code.  
While others were “present,” she was out here **leading the charge, architecting solutions, and carrying this project on her back** 🏆  

Rumor has it the compiler runs *because she permits it* ⚔️  
Build passes? Her doing.  
Code clean? Her standards.  
Enemies defeated? Signed off by her.  
Mana restored? Obviously.  

A truly independent, hardworking queen of the codebase 👸💻  

If anything breaks... Victoria said it's fine 👍

### CODE REVIEW

**Review by KaraboSamboTrainingCTU — APPROVED** [review]
We will deal with the warnings later. Seems like the build works just fine so we will accept it. Thank You👍🏾

**Review by ZandreCTU — APPROVED** [review]
Just add the option to play as a paladin class

File: Program.cs [hunk 1]
```diff
@@ -4,182 +4,137 @@
...
-                Console.WriteLine("Creating Character..." + _heroName);
+                // create player depending on class selected
                 Character _player = _heroClass switch
                 {
                     HeroClass.Warrior => new Warrior(_heroName),
                     HeroClass.Mage => new Mage(_heroName),
-                    HeroClass.Rogue => new Mage(_heroName),
-                    _ => new Warrior(_heroName)
+                    HeroClass.Rogue => new Rogue(_heroName),
+                    _ => new Warrior(_heroName) // fallback just in case
```
Comment (KaraboSamboTrainingCTU) [inline Program.cs:31]: Playable Palladin character here somewhere

**Review by Jan-LouisFourie — APPROVED** [review]
The paladin class is created, but cannot be selected. Everything else looks good

**Review by KaraboSamboTrainingCTU — APPROVED** [review]
